Repository 202303-PRM-TR-FEW/capstone-template-team-3, pull requests merged in 2023-08, with the labels that each got.

#117 Feat: added payment modal TR translation, Refactor: revised import folder locations
  app/[lng]/campaigns/[campaignId]/page.jsx
  app/[lng]/components/Card/Card.jsx
  app/[lng]/components/Navbar/Navbar.jsx
  app/[lng]/components/PaymentModal/PaymentModal.css
  app/[lng]/components/PaymentModal/PaymentModal.jsx
  app/[lng]/layout.jsx
  app/[lng]/page.jsx
  app/components/PaymentModal/PaymentModal.jsx
  app/i18n/locales/en/paymentModal.json
  app/i18n/locales/tr/paymentModal.json
Labels: enhancement, refactor

#141 Bug: My Campaings link in toggle and campaings filter link fixed
  app/[lng]/components/CategoryFilter/CategoryFilter.jsx
  app/[lng]/components/Navbar/Navbar.jsx
  app/[lng]/my-campaigns/page.jsx
Labels: bug

#145 Bug: undefined lng bug solved
  app/[lng]/campaigns/[campaignId]/page.jsx
  app/[lng]/campaigns/page.jsx
  app/[lng]/components/Navbar/Navbar.jsx
  app/[lng]/my-campaigns/page.jsx
Labels: bug

#152 Feat: Profile page, campaing duration and edit modal TR translation
  app/[lng]/campaigns/[campaignId]/page.jsx
  app/[lng]/campaigns/page.jsx
  app/[lng]/components/CampaignEditModal/CampaignEditModal.jsx
  app/[lng]/components/DeleteModal/DeleteModal.jsx
  app/[lng]/my-campaigns/page.jsx
  app/[lng]/profile/page.jsx
  app/[lng]/sign-in/page.jsx
  app/i18n/locales/en/campaignEdit.json
  app/i18n/locales/en/campaignId.json
  app/i18n/locales/en/deleteModal.json
  app/i18n/locales/en/profile.json
  app/i18n/locales/tr/campaignEdit.json
  app/i18n/locales/tr/campaignId.json
  app/i18n/locales/tr/deleteModal.json
  app/i18n/locales/tr/profile.json
Labels: enhancement

#181 Feat: Charity and Toastify TR translations
  app/[lng]/campaigns/[campaignId]/page.jsx
  app/[lng]/campaigns/page.jsx
  app/[lng]/components/CampaignEditModal/CampaignEditModal.jsx
  app/[lng]/components/DeleteModal/DeleteModal.jsx
  app/[lng]/components/KickOff/KickOff.jsx
  app/[lng]/components/Navbar/Navbar.jsx
  app/[lng]/components/PaymentModal/PaymentModal.jsx
  app/[lng]/layout.jsx
  app/[lng]/navigation/page.jsx
  app/[lng]/profile/page.jsx
  app/[lng]/sign-in/page.jsx
  app/[lng]/sign-up/page.jsx
  app/i18n/locales/en/campaign.json
  app/i18n/locales/en/campaignEdit.json
  app/i18n/locales/en/campaignId.json
  app/i18n/locales/en/deleteModal.json
  app/i18n/locales/en/kickOff.json
  app/i18n/locales/en/navbar.json
  app/i18n/locales/en/navigation.json
  app/i18n/locales/en/paymentModal.json
  app/i18n/locales/en/profile.json
  app/i18n/locales/en/sign-in.json
  app/i18n/locales/en/sign-up.json
  app/i18n/locales/tr/campaign.json
  app/i18n/locales/tr/campaignEdit.json
  app/i18n/locales/tr/deleteModal.json
  app/i18n/locales/tr/kickOff.json
  app/i18n/locales/tr/navbar.json
  app/i18n/locales/tr/navigation.json
  app/i18n/locales/tr/paymentModal.json
  app/i18n/locales/tr/profile.json
  app/i18n/locales/tr/sign-in.json
  app/i18n/locales/tr/sign-up.json
Labels: enhancement

#196 Style: minor changes on logo section
  app/[lng]/components/Footer/Footer.css
  app/[lng]/components/Footer/FooterBase.js
Labels: bug

#229 Fix: css adjustments
  app/[lng]/campaigns/[campaignId]/page.jsx
Labels: bug
